### ISSUE TITLE
Suspicious network activity

### ISSUE THREAD

**Issue by gjf** [ClownQq/YDArk#5]
Just wonder: why this piece of code tries to connect 47.102.143.195:9999 every time with start?

**Comment by ClownQq** [comment]
check update



---Original---
From: ***@***.***&gt;
Date: Fri, May 21, 2021 23:03 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ClownQq/YDArk] Suspicious network activity (#5)




 
Just wonder: why this piece of code tries to connect 47.102.143.195:9999 every time with start?

**Comment by gjf** [comment]
How to disable it?

**Comment by ClownQq** [comment]
> 如何禁用它？

The feature has been turned off in the latest version
